version: '2'

networks:
  default:
    external:
      name: fabnet

services:
  pngca:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=PnG
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.producer.net-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/e2f46f0947feac7ec036f9611743c0669b158c7fdf021fb6fc05040bc3bbb2d4_sk
    command: run_ca
    volumes:
      - ./init-config/crypto-config/peerOrganizations/producer.net/ca/:/etc/hyperledger/fabric-ca-server-config
      - ./scripts/run_ca:/usr/bin/run_ca
    container_name: pngca

  enduserca:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=EndUser
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.consumer.in-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/220f7b7e151e0553ee312ab35c3b70a5d8c54a8c5315310a8af46246880ae406_sk
    command: run_ca
    volumes:
      - ./init-config/crypto-config/peerOrganizations/consumer.in/ca/:/etc/hyperledger/fabric-ca-server-config
      - ./scripts/run_ca:/usr/bin/run_ca
    container_name: enduserca

  govca:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=Gov
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.regulator.gov-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/8fe1829c2c8dbdb593cf0705a901492577c5eed1f2a524ca81bcfe3b9555b2a4_sk
    command: run_ca
    volumes:
      - ./init-config/crypto-config/peerOrganizations/regulator.gov/ca/:/etc/hyperledger/fabric-ca-server-config
      - ./scripts/run_ca:/usr/bin/run_ca
    container_name: govca

  zookeeper0:
    container_name: zookeeper0
    extends:
      file: base/docker-compose-base.yaml
      service: zookeeper
    environment:
      - ZOO_MY_ID=1
      - ZOO_SERVERS=server.1=zookeeper0:2888:3888

  kafka0:
    container_name: kafka0
    extends:
      file: base/docker-compose-base.yaml
      service: kafka
    environment:
      - KAFKA_BROKER_ID=0
#      - KAFKA_MIN_INSYNC_REPLICAS=2
#      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper0:2181
    depends_on:
      - zookeeper0

  os11.bundler.org:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer
    container_name: os11.bundler.org
    depends_on:
      - kafka0
    volumes:
      - ./init-config/chcfg/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ./init-config/crypto-config/ordererOrganizations/bundler.org/orderers/os11.bundler.org/msp:/var/hyperledger/orderer/msp
      - ./init-config/crypto-config/ordererOrganizations/bundler.org/orderers/os11.bundler.org/tls:/var/hyperledger/orderer/tls

  unit21.producer.net:
    container_name: unit21.producer.net
    extends:
      file: ./base/peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=unit21.producer.net
      - CORE_PEER_ADDRESS=unit21.producer.net:7051
      - CORE_PEER_CHAINCODEADDRESS=unit21.producer.net:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=unit21.producer.net:7051
      - CORE_PEER_LOCALMSPID=PnGMSP
    volumes:
        - /var/run/:/host/var/run/
        - ./init-config/crypto-config/peerOrganizations/producer.net/peers/unit21.producer.net/msp:/etc/hyperledger/fabric/msp
        - ./init-config/crypto-config/peerOrganizations/producer.net/peers/unit21.producer.net/tls:/etc/hyperledger/fabric/tls

  unit22.producer.net:
    container_name: unit22.producer.net
    extends:
      file: ./base/peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=unit22.producer.net
      - CORE_PEER_ADDRESS=unit22.producer.net:7051
      - CORE_PEER_CHAINCODEADDRESS=unit22.producer.net:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=unit22.producer.net:7051
      - CORE_PEER_LOCALMSPID=PnGMSP
    volumes:
        - /var/run/:/host/var/run/
        - ./init-config/crypto-config/peerOrganizations/producer.net/peers/unit22.producer.net/msp:/etc/hyperledger/fabric/msp
        - ./init-config/crypto-config/peerOrganizations/producer.net/peers/unit22.producer.net/tls:/etc/hyperledger/fabric/tls

  family31.consumer.in:
    container_name: family31.consumer.in
    extends:
      file: ./base/peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=family31.consumer.in
      - CORE_PEER_ADDRESS=family31.consumer.in:7051
      - CORE_PEER_CHAINCODEADDRESS=family31.consumer.in:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=family31.consumer.in:7051
      - CORE_PEER_LOCALMSPID=EndUserMSP
    volumes:
        - /var/run/:/host/var/run/
        - ./init-config/crypto-config/peerOrganizations/consumer.in/peers/family31.consumer.in/msp:/etc/hyperledger/fabric/msp
        - ./init-config/crypto-config/peerOrganizations/consumer.in/peers/family31.consumer.in/tls:/etc/hyperledger/fabric/tls

  family32.consumer.in:
    container_name: family32.consumer.in
    extends:
      file: ./base/peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=family32.consumer.in
      - CORE_PEER_ADDRESS=family32.consumer.in:7051
      - CORE_PEER_CHAINCODEADDRESS=family32.consumer.in:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=family32.consumer.in:7051
      - CORE_PEER_LOCALMSPID=EndUserMSP
    volumes:
        - /var/run/:/host/var/run/
        - ./init-config/crypto-config/peerOrganizations/consumer.in/peers/family32.consumer.in/msp:/etc/hyperledger/fabric/msp
        - ./init-config/crypto-config/peerOrganizations/consumer.in/peers/family32.consumer.in/tls:/etc/hyperledger/fabric/tls

  office41.regulator.gov:
    container_name: office41.regulator.gov
    extends:
      file: ./base/peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=office41.regulator.gov
      - CORE_PEER_ADDRESS=office41.regulator.gov:7051
      - CORE_PEER_CHAINCODEADDRESS=office41.regulator.gov:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=office41.regulator.gov:7051
      - CORE_PEER_LOCALMSPID=GovMSP
    volumes:
        - /var/run/:/host/var/run/
        - ./init-config/crypto-config/peerOrganizations/regulator.gov/peers/office41.regulator.gov/msp:/etc/hyperledger/fabric/msp
        - ./init-config/crypto-config/peerOrganizations/regulator.gov/peers/office41.regulator.gov/tls:/etc/hyperledger/fabric/tls

  office42.regulator.gov:
    container_name: office42.regulator.gov
    extends:
      file: ./base/peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=office42.regulator.gov
      - CORE_PEER_ADDRESS=office42.regulator.gov:7051
      - CORE_PEER_CHAINCODEADDRESS=office42.regulator.gov:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=office42.regulator.gov:7051
      - CORE_PEER_LOCALMSPID=GovMSP
    volumes:
        - /var/run/:/host/var/run/
        - ./init-config/crypto-config/peerOrganizations/regulator.gov/peers/office42.regulator.gov/msp:/etc/hyperledger/fabric/msp
        - ./init-config/crypto-config/peerOrganizations/regulator.gov/peers/office42.regulator.gov/tls:/etc/hyperledger/fabric/tls
