NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.regulator.gov-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.regulator.gov-cert.pem
    OrganizationalUnitIdentifier: peer
