NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.consumer.in-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.consumer.in-cert.pem
    OrganizationalUnitIdentifier: peer
